# Generated by Django 4.1.3 on 2023-03-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_img', models.ImageField(blank=True, null=True, upload_to='b_id')),
                ('big_img', models.ImageField(blank=True, null=True, upload_to='b_id')),
            ],
        ),
    ]
