# Generated by Django 4.1.3 on 2023-03-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_b'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='b',
            new_name='bCategory',
        ),
    ]
