# Generated by Django 4.1.3 on 2023-03-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_b_bcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bCategory',
            new_name='b',
        ),
    ]
