# Generated by Django 4.1.3 on 2023-03-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_bcategory_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='Btom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bsort', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'btom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messe',
            fields=[
                ('messe_id', models.AutoField(primary_key=True, serialize=False)),
                ('veranstalter_id', models.PositiveIntegerField()),
                ('zentren_id', models.IntegerField(blank=True, null=True)),
                ('gruendung', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('messe_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('messe_url', models.CharField(max_length=255)),
                ('messe_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('messe_fax', models.CharField(blank=True, max_length=255, null=True)),
                ('messe_land', models.PositiveIntegerField(blank=True, null=True)),
                ('messe_ort', models.IntegerField(blank=True, null=True)),
                ('messe_plz', models.CharField(blank=True, max_length=255, null=True)),
                ('messe_email', models.CharField(max_length=255)),
                ('messe_strasse', models.CharField(blank=True, max_length=255, null=True)),
                ('messe_firma', models.CharField(blank=True, max_length=255, null=True)),
                ('messe_adresse', models.TextField(blank=True, null=True)),
                ('regional', models.PositiveIntegerField()),
                ('empfehlung', models.PositiveIntegerField(blank=True, null=True)),
                ('turnus_id', models.PositiveIntegerField(blank=True, null=True)),
                ('zutritt_id', models.PositiveIntegerField(blank=True, null=True)),
                ('zutritt_text_id', models.IntegerField(blank=True, null=True)),
                ('zutritt_covid_id', models.PositiveIntegerField(blank=True, null=True)),
                ('messe_angelegt', models.DateTimeField()),
                ('messe_angelegt_von', models.PositiveIntegerField()),
                ('messe_update', models.DateTimeField(blank=True, null=True)),
                ('messe_termin_email', models.DateTimeField(blank=True, null=True)),
                ('messe_status', models.CharField(max_length=1)),
                ('eintritt_frei', models.IntegerField(blank=True, null=True)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('google', models.IntegerField(blank=True, null=True)),
                ('timetable', models.CharField(max_length=255)),
                ('oeffnungurl', models.CharField(blank=True, max_length=255, null=True)),
                ('messe_geprueft', models.DateTimeField(blank=True, null=True)),
                ('freelancer_id', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messe',
                'managed': False,
            },
        ),
    ]
